%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[192.168.1.0/24]"

default-rule-path: /etc/suricata/rules
rule-files:
  - custom.rules

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
            payload: yes
            metadata: yes
            tagged-packets: yes
